image: mileschou/phalcon:7.1-fpm

before_script:
    - apt-get -qq update
    - apt-get -y -qq install  git unzip
    - curl -Lo /usr/local/bin/composer https://getcomposer.org/composer.phar
    - chmod +x /usr/local/bin/composer

stages:
    - test

test:
    stage: test
    script:
        - make update
        - make test-all
